// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbUK2g_ApBUVgXQ0In-hS_LQTnlL-BuKc',
    appId: '1:823861954017:web:5a44d4843a15eff50efea0',
    messagingSenderId: '823861954017',
    projectId: 'Angel-c53f2',
    authDomain: 'Angel-c53f2.firebaseapp.com',
    storageBucket: 'Angel-c53f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbKROJNPbrxs5gdiBfLOyOGuqnX7hb70',
    appId: '1:823861954017:android:2b3542202adc15960efea0',
    messagingSenderId: '823861954017',
    projectId: 'Angel-c53f2',
    storageBucket: 'Angel-c53f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-XjYobekxJh1um7trGCo7n_u5nJveSF0',
    appId: '1:823861954017:ios:0cbab3eea2b9f8330efea0',
    messagingSenderId: '823861954017',
    projectId: 'Angel-c53f2',
    storageBucket: 'Angel-c53f2.appspot.com',
    iosClientId:
        '823861954017-gt3mqmgtmg5gr7uo5hv6fod83jik6sh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.Angel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-XjYobekxJh1um7trGCo7n_u5nJveSF0',
    appId: '1:823861954017:ios:0cbab3eea2b9f8330efea0',
    messagingSenderId: '823861954017',
    projectId: 'Angel-c53f2',
    storageBucket: 'Angel-c53f2.appspot.com',
    iosClientId:
        '823861954017-gt3mqmgtmg5gr7uo5hv6fod83jik6sh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.Angel',
  );
}
